### ISSUE TITLE
Set up verification actions/CI

### ISSUE THREAD

**Issue by dzirbel** [thumbtack/thumbprint-android#17]
We should have pull requests/merges/etc verified, possibly just via GitHub Actions. The verification itself can just be `./gradlew check`, I believe. That will run detekt, lint, compilation, and tests. It's a bit overkill in that it runs both for the `debug` and `release` variants, but should still only take about a minute given this is a small project right now.

**Comment by mallikapotter** [comment]
Going to add these using GitHub Actions once we get the aar working (I didn't add it previously because it required the repo to be public, which only just happened)
